name: Build Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 手動でワークフローを実行できるようにする

jobs:
  build:
    runs-on: windows-latest  # Windows環境で実行

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # electron-nextの型定義問題を解決
      - name: Create electron-next type definition if missing
        run: |
          if (-not (Test-Path "electron-src\electron-next.d.ts")) {
            echo "declare module 'electron-next';" | Out-File -FilePath "electron-src\electron-next.d.ts" -Encoding utf8
          }

      - name: Build Windows application
        run: pnpm dist --win --publish=never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          ELECTRON_BUILDER_PUBLISH: never

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            dist/*.exe
            dist/win-unpacked/ 