name: ポータブルEXEビルド

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:  # 手動実行用

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: pnpmのセットアップ
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      
      - name: pnpmキャッシュの設定
        uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
            renderer/.next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - name: 依存関係のインストール
        run: pnpm install
      
      - name: Electronメインプロセスのコンパイル
        run: pnpm compile-electron
      
      - name: renderer用next.configのコピーと設定
        run: |
          cp next.config.js renderer/next.config.js
          (Get-Content renderer/next.config.js) -replace 'distDir:.+,', 'distDir: ".next",' | Set-Content renderer/next.config.js
      
      - name: Next.jsアプリのビルド
        run: |
          cd renderer
          npx next build
      
      - name: ポータブルEXEファイルのビルド
        run: pnpm electron-builder build --win portable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ビルド成果物のアップロード
        uses: actions/upload-artifact@v3
        with:
          name: sql-client-portable
          path: dist/*.exe
          retention-days: 30 