# SQLクライアントアプリケーションのビルドとリリースワークフロー
# このワークフローではWindows向けのElectronアプリケーションをビルドし、
# タグ付けされた場合は自動的にGitHubリリースを作成します。
name: Hello World Test

# ワークフローのトリガー設定
on:
  push:
    branches: [ main ]   # メインブランチへのプッシュ時に実行
    tags:
      - 'v*'            # vから始まるタグ（例：v1.0.0）がプッシュされた時に実行
  pull_request:
    branches: [ main ]   # メインブランチへのプルリクエスト時に実行
  workflow_dispatch:     # 手動でワークフローを実行するオプション

# 実行するジョブの定義
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Install dependencies
      run: |
        pnpm install
    
    - name: ディレクトリ構造を確認・作成
      run: |
        echo "現在のディレクトリ構造を表示"
        ls -la
        echo "rendererディレクトリの内容"
        ls -la renderer || mkdir -p renderer
        echo "renderer/appディレクトリの作成"
        mkdir -p renderer/app
        echo "必要なNext.jsのファイルを作成"
        echo "export default function Page() { return <div>Hello World</div> }" > renderer/app/page.tsx
        echo "export default function Layout({ children }) { return <html><body>{children}</body></html> }" > renderer/app/layout.tsx
        echo "body { font-family: sans-serif; }" > renderer/app/globals.css
        echo "@tailwind base; @tailwind components; @tailwind utilities;" >> renderer/app/globals.css
        echo "import './globals.css'; export const metadata = { title: 'SQL Client' }; export default function RootLayout({ children }) { return <html lang=\"ja\"><body>{children}</body></html>; }" > renderer/app/layout.tsx
        echo "ディレクトリ作成完了"
        ls -la renderer/app
        
    - name: Create renderer/next.config.js
      run: |
        cp next.config.js renderer/next.config.js
        sed -i 's/distDir:.*/distDir: ".next",/' renderer/next.config.js
        
    - name: Build Next.js App
      run: |
        cd renderer
        npx next build
      
    - name: Test Hello World
      run: |
        echo "Testing Hello World SQL Client Application"
        echo "Build successful!"

# GitHubリリース作成ジョブ（タグ付けされた場合のみ実行）
release:
  needs: test                  # testジョブが成功した後に実行
  if: startsWith(github.ref, 'refs/tags/v')  # vから始まるタグの場合のみ実行
  runs-on: ubuntu-latest        # リリース作成はUbuntu環境で実行
  
  steps:
    # ステップ1: ビルドジョブでアップロードした成果物をダウンロード
    - name: ビルド成果物のダウンロード
      uses: actions/download-artifact@v4  # 最新バージョンv4を使用
      with:
        name: electron-app      # ダウンロードする成果物の名前（testジョブでアップロードしたもの）
        path: dist              # ダウンロード先のパス
        
    # ステップ2: GitHubリリースの作成と.exeファイルの添付
    - name: リリースの作成
      uses: softprops/action-gh-release@v1  # GitHubリリース作成アクション
      with:
        files: dist/*.exe                   # リリースに添付するファイル
        generate_release_notes: true        # コミットメッセージから自動的にリリースノートを生成
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHubが自動的に提供するトークンを使用 